name: warehouse_management_system
description: A comprehensive warehouse management system built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  file_picker: ^10.2.0
  mime: ^2.0.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
dependency_overrides:
  intl: ^0.18.1